//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_EntityFrameworkModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veli
    {
        public int VeliId { get; set; }
        public string VeliAdi { get; set; }
        public string VeliSoyadi { get; set; }

        public override string ToString()
        {
            return this.VeliAdi + " " + this.VeliSoyadi;
        }
    }
}
